name: ms-gen
channels:
- pytorch
- conda-forge
dependencies:
- python=3.8.*
- matplotlib=3.4.*
- rdkit=2021.03.*
- pytorch-lightning=1.6.* #1.7
- einops
- pip=21.2.*
- ipykernel=6.0.*
- pytorch::pytorch=1.9.* #- dgl=0.7.*
- nb_conda_kernels=2.3.*
- seaborn=0.11.*
- h5py
- ray-tune
- umap-learn
- optuna
- cudatoolkit=11.1 # may need to modify if cpu only
  #- pytorch::torchvision
  #- torchmetrics
